### ISSUE TITLE
Manufacturer name always shows ESTA

### ISSUE THREAD

**Issue by gobo-ws** [Bannsaenger/node-red-contrib-artnet-controller#1]
Manufacturer name always shows ESTA but the product name changes though when changing the hex value for the OEM code.
Example 0x2A7E (Product: DARKMOON)
Tested with DMX-Workshop from Artistic Licence  

![Screenshot 2022-12-22 183115](https://user-images.githubusercontent.com/14245452/209192680-d76c5b0e-757e-4228-9c95-83cb86ac76b4.png)

**Comment by Bannsaenger** [comment]
The OEM Code does not include the manufacturer. 
I added the possibility to configure the manufacturer code (ESTA code) in the Art-Net Controller node.

![grafik](https://user-images.githubusercontent.com/26897700/209687389-cd55dd1d-f3f2-40b3-a1b5-22712ba2735c.png)

**Comment by gobo-ws** [comment]
Hi, thanks for adding this 👍🏻
