### ISSUE TITLE
Git is required to install the node.  This is not mentioned in the readme.

### ISSUE THREAD

**Issue by colinl** [Bannsaenger/node-red-contrib-artnet-controller#2]
Could you add the git requirement to the readme please?  Then it will be less likely that we will get 'failed to install' questions about it on the node red forum.  Thanks.
Assuming that there is not a way to remove the requirement, which would be even better.

**Comment by Bannsaenger** [comment]
I switched back to the "non git based" dependency.
See version 0.1.3
Thanks for your comment.
