### ISSUE TITLE
No data over other Network Interface

### ISSUE THREAD

**Issue by bugbig09** [Bannsaenger/node-red-contrib-artnet-controller#6]
Data is always sent via the eth0 network interface. If I select the interface enp1s0u2 with 2.0.0.2, data is still only sent via eth0. I have run a tcpdump, there is really only something coming via the eth0 interface.
<img width="504" alt="Bildschirmfoto 2024-03-24 um 13 48 42" src="https://github.com/Bannsaenger/node-red-contrib-artnet-controller/assets/4692557/a643a725-988d-4f81-8d6e-4aae78f734a2">
<img width="692" alt="Bildschirmfoto 2024-03-24 um 13 49 16" src="https://github.com/Bannsaenger/node-red-contrib-artnet-controller/assets/4692557/717eb249-75e2-4e06-8e3d-43aa99ce0ea2">

**Comment by Bannsaenger** [comment]
Hi,
you are using a Class C network mask on your interface.
Then the brodcast address of this interface is:
![grafik](https://github.com/Bannsaenger/node-red-contrib-artnet-controller/assets/26897700/82fc65c5-1f1d-4d08-b0dd-15314020e418)
when you use the 2.255.255.255 these data packets will not be sent necessarily via this interface.
Try to use 2.0.0.255 or change your network mask to 255.0.0.0
Hope this will fix ist.

**Comment by bugbig09** [comment]
Thank you, that was my mistake. I tried again and again for 3 days.
